title: Pigeoncoin
email: contact@pigeoncoin.org
tagline: Messaging and payments for everyone.
description: >
  Messaging and payments for everyone. Security by Blockchain.


# config
baseurl: /test # baseurl: null # when deployed to pigeoncoin.org

# social links
social:
    discord: https://discord.gg/SZcf63h
    twitter: https://twitter.com/Pigeoncoin
    github: https://github.com/Pigeoncoin
    reddit: https://www.reddit.com/r/Pigeoncoin/
    telegram: https://t.me/Pigeoncoin
    medium: https://medium.com/@pigeoncoin

# download links
download:
  macOS: https://github.com/Pigeoncoin/pigeoncoin/releases/download/v0.15.99.0/Pigeon-Qt.dmg
  windows: https://github.com/Pigeoncoin/pigeoncoin/releases/download/v0.15.99.0/pigeoncoin-windows_v0.15.99.0.zip
  linux: https://github.com/Pigeoncoin/pigeoncoin/releases/download/v0.15.99.0/pigeoncoin-linux_v0.15.99.0.tar.gz

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# collections:
# - roadmap


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
