title: Pigeoncoin
email: contact@pigeoncoin.org
tagline: Digital freedom
description: >
  Messaging and payments for everyone. Security by Blockchain.


# config
baseurl: null # baseurl: null # when deployed to pigeoncoin.org

# social links
social:
    Discord: https://discord.gg/SZcf63h
    Twitter: https://twitter.com/Pigeoncoin
    Github: https://github.com/Pigeoncoin
    Reddit: https://www.reddit.com/r/Pigeoncoin/
    Telegram: https://t.me/Pigeoncoin
    Medium: https://medium.com/@pigeoncoin

# download links
wallets:
  macOS: https://github.com/Pigeoncoin/pigeoncoin/releases/download/v0.15.99.2/pigeon-0.15.99-macOS.dmg
  Windows: https://github.com/Pigeoncoin/pigeoncoin/releases/download/v0.15.99.2/pigeon-0.15.99-win64.zip
  Linux: https://github.com/Pigeoncoin/pigeoncoin/releases/download/v0.15.99.2/pigeon-0.15.99-x86_64-linux-gnu.tar.gz

miners:
  Nvidia: https://github.com/brian112358/nevermore-miner/releases/
  AMD: https://github.com/brian112358/avermore-miner/releases

exchanges:
  CryptoBridge: https://crypto-bridge.org/

broadcasts:
  'May 12': https://www.dropbox.com/s/l788d4bivpmkx3s/may-12-fireside-trimmed.mp3?dl=0
  'April 29': https://www.dropbox.com/s/d3t0v1o3jpwoc67/april-29-fireside-trimmed.mp3?dl=0
  'April 15': https://www.dropbox.com/s/rg3crkifhbyaj3j/april-15-fireside-full.mp3?dl=0


pool:
  website: https://pool.pigeoncoin.org
  address: https://pool.pigeoncoin.org:3663

explorer:
  website: https://explorer.pigeoncoin.org

donate:
  pgn: PDiZ89gk5HMqwrcGp6Hs9WdgFALzLbD4HG
  btc: 1NaVP4cKiWY6MxSDkTCZ2kh5Xm3coA27Qv

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# collections:
# - roadmap

sass:
  sass_dir: _sass
  style: compressed


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
